// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/consensus.proto

package consensus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *int64                 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_grpc_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpc_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *int64                 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_grpc_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_grpc_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

var File_grpc_consensus_proto protoreflect.FileDescriptor

const file_grpc_consensus_proto_rawDesc = "" +
	"\n" +
	"\x14grpc/consensus.proto\"'\n" +
	"\aRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"%\n" +
	"\x05Reply\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2%\n" +
	"\x04Node\x12\x1d\n" +
	"\aMessage\x12\b.Request\x1a\x06.Reply\"\x00B\rZ\v./consensusb\beditionsp\xe8\a"

var (
	file_grpc_consensus_proto_rawDescOnce sync.Once
	file_grpc_consensus_proto_rawDescData []byte
)

func file_grpc_consensus_proto_rawDescGZIP() []byte {
	file_grpc_consensus_proto_rawDescOnce.Do(func() {
		file_grpc_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_consensus_proto_rawDesc), len(file_grpc_consensus_proto_rawDesc)))
	})
	return file_grpc_consensus_proto_rawDescData
}

var file_grpc_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_consensus_proto_goTypes = []any{
	(*Request)(nil), // 0: Request
	(*Reply)(nil),   // 1: Reply
}
var file_grpc_consensus_proto_depIdxs = []int32{
	0, // 0: Node.Message:input_type -> Request
	1, // 1: Node.Message:output_type -> Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_consensus_proto_init() }
func file_grpc_consensus_proto_init() {
	if File_grpc_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_consensus_proto_rawDesc), len(file_grpc_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_consensus_proto_goTypes,
		DependencyIndexes: file_grpc_consensus_proto_depIdxs,
		MessageInfos:      file_grpc_consensus_proto_msgTypes,
	}.Build()
	File_grpc_consensus_proto = out.File
	file_grpc_consensus_proto_goTypes = nil
	file_grpc_consensus_proto_depIdxs = nil
}
